Checks:
 - Protocol: tcp
   Parameters:
     Host: localhost
     Port: [9000, 80]
     SecurePort: 
     Timeout: 10
 - Protocol: tcp
   Parameters:
     Host: somehost
     Port: [9001, 8080]
     SecurePort: 
     Timeout: 10